### ISSUE TITLE
what a silly repository

### ISSUE THREAD

**Issue by p-i-c-o** [CatGuyMoment/silly-utils#2]
silly boy

**Comment by CatGuyMoment** [comment]
ikr

**Comment by p-i-c-o** [comment]
POV: You are in this repository

![image](https://github.com/CatGuyMoment/silly-utils/assets/95228665/e579bf44-3a97-4025-bf2a-8ce6b3393c33)

(he's a silly boy)

**Comment by CatGuyMoment** [comment]
literally me
