### ISSUE TITLE
silly cover petition

### ISSUE THREAD

**Issue by p-i-c-o** [CatGuyMoment/silly-utils#3]
what a silly cover!

petition to add `![Silly Cover](silly-cover.png)` to the readme
![silly-cover](https://github.com/CatGuyMoment/silly-utils/assets/95228665/dbf53c92-d854-4796-9df6-adf0707f3820)

**Comment by CatGuyMoment** [comment]
y e s.

**Comment by CatGuyMoment** [comment]
it is done.
